### ISSUE TITLE
Mirador another instance need page reload 

### ISSUE THREAD

**Issue by DigitLib** [nakamura196/nuxt-mirador#1]
Hello,
First great thanks for this integration! 
I have noted that mirador is in a mess when go to other instance.
It works fine in dev mode but when generate it starts to make a problem.
![image](https://user-images.githubusercontent.com/16822119/165498027-ced79b78-f988-4dd9-881e-6fc4e12a087f.png)
It fixes after page reload .

Again,
Thank you for this implementation!

**Comment by DigitLib** [comment]
Issue solved!
**default.vue**
`export default {

  computed: {
    miradorViewerOptions() {

      const manifest = "https://iiif.bodleian.ox.ac.uk/iiif/manifest/e32a277e-91e2-4a6d-8ba6-cc4bad230410.json"
      const config = {
        id: "demo",
        windows: [
          {
            manifestId: manifest,
          },
        ],
      }
      // Mirador.viewer(config, [...miradorImageToolsPlugin])
      return config;
    },
  },
  mounted() {

    this.mirador = Mirador.viewer(this.miradorViewerOptions, [...miradorImageToolsPlugin]);
  },

  beforeDestroy() {
    this.mirador.unmount()
  }
}
</script>
`
**embedded.vue**

`data() {
    return {
      canvas: ""
    }
  },
  computed: {
    miradorViewerOptions() {

      const config = {
        id: "mirador",
        windows: [
          {
            id: 'known-window-id',
            manifestId: this.manifestId,
          },
        ],
        window: {
          allowClose: false,
          allowMaximize: false,
          allowFullscreen: true,
          hideWindowTitle: true,
        },
        workspaceControlPanel: {
          enabled: false,
        },
      }
      // miradorInstance = Mirador.viewer(config, [...miradorImageToolsPlugin])
      return config;
    },
  },
  watch: {
    canvas() {
      // We create the action first. Note we are using a specified `windowId` here. This could be accessed from the store instead of specifying upfront.
      const action = Mirador.actions.setCanvas('known-window-id', this.canvas)
      // Now we can dispatch it.
      miradorInstance.store.dispatch(action)
    },
  },

  mounted() {
       miradorInstance = Mirador.viewer(this.miradorViewerOptions, [...miradorImageToolsPlugin]);
  },
  beforeDestroy() {
    miradorInstance.unmount()
  },

  methods:{
    zoom(){
      // Box to zoom to
      const boxToZoom = {
        x: 1420,
        y: 1831,
        width: 800,
        height: 1195
      };

      const zoomCenter = {
        x: boxToZoom.x + boxToZoom.width / 2,
        y: boxToZoom.y + boxToZoom.height / 2
      };
      const action = Mirador.actions.updateViewport('known-window-id', {
        x: zoomCenter.x,
        y: zoomCenter.y,
        zoom: 1 / boxToZoom.width
      });

      miradorInstance.store.dispatch(action);

    }
  }
}
</script>
`

Generated and check it work. No problem with MUI.

Thank you for this implementation.

Best,
Andrija

**Comment by DigitLib** [comment]
I can make PR if you like?

**Comment by nakamura196** [comment]
Thanks!
I appreciate your PR.

**Comment by DigitLib** [comment]
Thank you for implementation!

**Comment by nakamura196** [comment]
I really appreciate your help!
